### ISSUE TITLE
Add rounded edges at the ends

### ISSUE THREAD

**Issue by isadoraoliv** [stefanJi/IntervalProgressBar#2]
Hi!
Could you add in these versions these rounded edges as they are in the preview?
Thanks

<img width="416" alt="Screen Shot 2020-04-24 at 13 56 46" src="https://user-images.githubusercontent.com/28692397/80237969-f92ab080-8633-11ea-95de-e4a91de737e4.png">

**Comment by stefanJi** [comment]
The `radius` property could make edges to round.

**Comment by isadoraoliv** [comment]
Its works! Thanks :)
